USE MASTER 
GO
--alter database QLHOSOUNGTUYEN set single_user with rollback immediate
DROP DATABASE IF EXISTS QLHOSOUNGTUYEN
GO
CREATE DATABASE QLHOSOUNGTUYEN
GO
USE QLHOSOUNGTUYEN
GO
-- DROP TABLE
DROP TABLE IF EXISTS THONGTINCHIENLUOC
GO
DROP TABLE IF EXISTS CHIENLUOCUUDAI
GO
DROP TABLE IF EXISTS UNGTUYEN
GO
DROP TABLE IF EXISTS UNGVIEN
GO
DROP TABLE IF EXISTS HOADONTHANHTOAN
GO
DROP TABLE IF EXISTS THONGTINDANGTUYEN
GO
DROP TABLE IF EXISTS THANHVIEN
GO
DROP TABLE IF EXISTS NHANVIEN
GO
--------------- CREATE TABLE ------------------------
CREATE TABLE THANHVIEN(
	MaDN VARCHAR(6) PRIMARY KEY,
	TenCongTy NVARCHAR(100),
	Email VARCHAR(100),
	NguoiDaiDien NVARCHAR(100),
	MaSoThue VARCHAR(13),
	MaNV VARCHAR(6),
)
GO
CREATE TABLE THONGTINCHIENLUOC(
	MaDN VARCHAR(6),
	MaCL VARCHAR(6),
	PRIMARY KEY (MaDN, MaCL)
)
GO
CREATE TABLE CHIENLUOCUUDAI(
	MaCL VARCHAR(6),
	NgayBatDau DATE,
	NgayKetThuc DATE,
	DieuKien NVARCHAR(100),
	MoTa NVARCHAR(100),
	GiaTriUuDai INT,
	PRIMARY KEY (MaCL)
)
GO
CREATE TABLE NHANVIEN(
	MaNV VARCHAR(6),
	HoTen NVARCHAR(100),
	ChucVu NVARCHAR(50),
	NgaySinh DATE,
	DiaChi NVARCHAR(100),
	SoDienThoai VARCHAR(10),
	MatKhau VARCHAR(40),
	PRIMARY KEY (MaNV)
)
GO
CREATE TABLE UNGVIEN(
	MaUV VARCHAR(6),
	HoTen NVARCHAR(100),
	NgaySinh DATE,
	DiaChi NVARCHAR(100),
	SoDienThoai VARCHAR(10),
	MaNV VARCHAR(6), -- NHAN VIEN KIEM DUYET HO SO
	PRIMARY KEY (MaUV)
)
GO
CREATE TABLE UNGTUYEN(
	MaUV VARCHAR(6),
	MaDT VARCHAR(6),
	BangCap NVARCHAR(100),
	TinhTrang NVARCHAR(20),
	ChungTu NVARCHAR(100),
	HoSo NVARCHAR(100),
	PRIMARY KEY (MaUV, MaDT)
)
GO
CREATE TABLE THONGTINDANGTUYEN(
	MaDT VARCHAR(6) PRIMARY KEY ,
	ThongTinYeuCau NVARCHAR(100),
	NgayBatDau DATE,
	NgayKetThuc DATE,
	SLTuyenDung INT,
	ViTriTuyenDung NVARCHAR(50),
	HinhThucDangTuyen NVARCHAR(50),
	TinhTrang NVARCHAR(30), --Da Duoc Dang Hay Chua
	GiaTien INT,
	MaDN VARCHAR(6)
)
GO
CREATE TABLE HOADONTHANHTOAN(
	NgayLap DATE,
	SoTienCanThanhToan INT,
	SoTienDaThanhToan INT,
	SoTienConLai INT,
	DotThanhToan INT,
	MaThe NVARCHAR(20),
	MaCL VARCHAR(6),
	HinhThucThanhToan NVARCHAR(30),
	MaDT VARCHAR(6),

	PRIMARY KEY(MaDT, DotThanhToan)
)
GO
---------------------------KHOA NGOAI--------------------------------
-- THANH VIEN
ALTER TABLE THANHVIEN
ADD CONSTRAINT FK_THANHVIEN_NHANVIEN
FOREIGN KEY(MaNV)
REFERENCES NHANVIEN
GO
-- THONGTINCHIENLUOC
ALTER TABLE THONGTINCHIENLUOC
ADD CONSTRAINT FK_THONGTINCHIENLUOC_THANHVIEN
FOREIGN KEY(MaDN)
REFERENCES THANHVIEN
GO
ALTER TABLE THONGTINCHIENLUOC
ADD CONSTRAINT FK_THONGTINCHIENLUOC_CHIENLUOCUUDAI
FOREIGN KEY(MaCL)
REFERENCES CHIENLUOCUUDAI
GO
-- UNGVIEN
ALTER TABLE UNGVIEN
ADD CONSTRAINT FK_UNGVIEN_NHANVIEN
FOREIGN KEY(MaNV)
REFERENCES NHANVIEN
GO
-- UNGTUYEN
ALTER TABLE UNGTUYEN
ADD CONSTRAINT FK_UNGTUYEN_UNGVIEN
FOREIGN KEY(MaUV)
REFERENCES UNGVIEN
GO
ALTER TABLE UNGTUYEN
ADD CONSTRAINT FK_UNGTUYEN_THONGTINDANGTUYEN
FOREIGN KEY(MaDT)
REFERENCES THONGTINDANGTUYEN
GO
-- THONGTINDANGTUYEN
ALTER TABLE THONGTINDANGTUYEN
ADD CONSTRAINT FK_THONGTINDANGTUYEN_THANHVIEN
FOREIGN KEY(MaDN)
REFERENCES THANHVIEN
GO
-- THANHTOAN
ALTER TABLE HOADONTHANHTOAN
ADD CONSTRAINT FK_HOADONTHANHTOAN_THONGTINDANGTUYEN
FOREIGN KEY(MaDT)
REFERENCES THONGTINDANGTUYEN
GO
ALTER TABLE HOADONTHANHTOAN
ADD CONSTRAINT FK_HOADONTHANHTOAN_CHIENLUOCUUDAI
FOREIGN KEY(MaCL)
REFERENCES CHIENLUOCUUDAI
